@database=devsales
@Authorization=Bearer eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI5IiwidW5pcXVlX25hbWUiOiJwYXRlbCIsIm5iZiI6MTU4MTgyNTg0NCwiZXhwIjoxNTgyNjg5ODQ0LCJpYXQiOjE1ODE4MjU4NDR9.jfTA3EJN1pn0HWspGuy2tp6c7ZCAx3X8iuNjOd5ZuzURi7_XHyImPC8UeuEza2X6WofPCrRsW-BAdpd7HqXppg
Get http://Localhost:5000/api/values/1 HTTP/1.1
//database={{database}}

###

Get http://Localhost:5000/api/values/1 HTTP/1.1
Authorization: {{Authorization}}
###


POST http://Localhost:5000/api/auth/register  
Content-Type: application/json

{
   "username":"John",
   "password":"password" 
}
###

POST http://Localhost:5000/api/auth/login
Content-Type: application/json

{
   "username":"John",
   "password":"password" 
}

###
Get http://Localhost:5000/api/users/
Authorization: {{Authorization}}

###
Get http://Localhost:5000/api/users?pageNumber=2&pageSize=3
Authorization: {{Authorization}}

###
POST http://Localhost:5000/api/users/9/messages  HTTP/1.1
Authorization: {{Authorization}}
Content-Type: application/json

{
   "recipientId": 1,
   "content": "Hi hello how are you"
}
